### PR TITLE
Added round trip tests for uu

### LINKED ISSUE #21: Write round-trip tests for the `uu` module
[The `uu` module](https://docs.python.org/3/library/uu.html) could do with some round-trip tests!  Imitating the `binascii` tests in `tests/test_encoding_decoding.py` would be a good start, though you'll need to use `io.BytesIO` since `uu` takes file objects rather than bytes.

### PR DESCRIPTION
**Pull request by akash-suresh**
Resolves https://github.com/Zac-HD/stdlib-property-tests/issues/21

### CODE REVIEW

**Comment by akash-suresh** [comment]
Hey @Zac-HD! I have added round trip tests for `uu`. Please have a look.

**Review by Zac-HD — APPROVED** [review]
Looks great!  Thanks @akash-suresh!

**Comment by Zac-HD** [comment]
This is exactly how I would write it, I don't have any suggestions at all :grin:

**Comment by akash-suresh** [comment]
Haha awesome 👻 🎉

**Pull request merged**
